name: Build Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Build the binary
      - name: Build binary
        run: |
          pyinstaller --onefile StochasticGradientDescent.py
          mkdir -p dist/bin
          mv dist/StochasticGradientDescent dist/bin/

      # Upload the binary as an artifact
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: StochasticGradientDescent
          path: dist/bin/StochasticGradientDescent
